### ISSUE TITLE
Feature Request: Support rust bindings for Recognition

### ISSUE THREAD

**Issue by Inrixia** [scaranaraa/Node-Shazam#2]
I have ported the shazamio-core **(https://github.com/shazamio/shazamio-core)** python rust bindings to WebAssembly **(https://github.com/Inrixia/shazamio-core)** for use in node and the browser.

Having support for using the native rust bindings would allow much faster Recognition.

The ShazamIO python library has methods for using both as can be seen from its readme:
```python
async def main():
  shazam = Shazam()
  # out = await shazam.recognize_song('dora.ogg') # slow and deprecated, don't use this!
  out = await shazam.recognize('dora.ogg')  # rust version, use this!
  print(out)
```

So I would think that following the same format and adding the rust bindings while keeping the original methods would be a good approach.

**Comment by Inrixia** [comment]
My wasm port also has the added benefit of not requiring **ffmpeg** at all working entirely in memory.

**Comment by duckyies** [comment]
will look into it! thanks

**Comment by Inrixia** [comment]
I'm in the middle of making some improvements to how stuff is handled but the api is fairly stable now.

The only big change I have left to implement which will be done soon is only calculating the signatures as requested by js, which is fairly straightforward.

If you have any questions please do reach out!
