### ISSUE TITLE
Call signature.free() when done & update to latest shazamio-core

### ISSUE THREAD

**Issue by Inrixia** [scaranaraa/Node-Shazam#3]
Hey, thanks for implementing #2!

It looks like you implemented your changes just before I pushed some significant improvements in v1.3.0.

Of specific note is
 - Only actually processing a signature when js accesses the value https://github.com/Inrixia/shazamio-core/commit/f5eb2132ea98ebc111a1661f5bb516c02d6c18fc
 - Resample on demand too https://github.com/Inrixia/shazamio-core/commit/e554c1cbd50ab9b9672f9486e8bd20460f42a784

These two changes mean that you can request the 12s segments for an entire file and instead of taking up to 5s its only around 500ms for the initial read and then 200ms per segment.

Also I noticed that you are not calling `segment.free()` in your code. That's partially on me, I did not have the note about freeing memory in my readme until recently.
https://github.com/scaranaraa/Node-Shazam/blob/af29228c1728cecf608c0cfc8911066ca310ff40/src/api.ts#L182

You should free the memory of a segment once you are done using its properties, note this will cause any future attempts to access its properties panic.

I don't foresee much in the way of changes happening now that I've properly sorted everything and optimized performance so this should be the final changes for now.

**Comment by Inrixia** [comment]
I'm using this nifty helper method in one of my projects, if you wanted a easy way to deal with freeing memory.

```ts
export const using = async <T>(signatures: DecodedSignature[], fun: (signatures: ReadonlyArray<DecodedSignature>) => T) => {
	const ret = await fun(signatures);
	for (const signature of signatures) signature.free();
	return ret;
};
```

**Comment by duckyies** [comment]
Hey, thanks for that! 
I completely missed free() before, now it should properly free up the memory

Do let me know about any further optimizations or changes needed

**Comment by Inrixia** [comment]
Willdo! :)

Also good news, I just tested and videos seem to just work.

**Comment by Inrixia** [comment]
Closing as implemented in https://github.com/scaranaraa/Node-Shazam/commit/6b004268c8920642702775caaff72a4ab01b005d thx!
