### ISSUE TITLE
Take middle signature for accuracy

### ISSUE THREAD

**Issue by Inrixia** [scaranaraa/Node-Shazam#4]
Hi, so one thing I didn't think to mention when you ported over to my fork of https://github.com/Inrixia/shazamio-core the original code returned the middle of the samples. My code returns an array of signatures where the actual signature calculation is done when accessing the properties of the signature in node.

All this said its probably a good idea to take the middle signature as you will get better results than just taking the first (the middle of the song vs the start). Though I personally also loop over signatures until I get a match in some of my implementations like in [shazamwow.com](https://github.com/Inrixia/neptune-plugins) or my [tidal plugin](https://github.com/Inrixia/neptune-plugins)

You are taking the first signature returned here
https://github.com/scaranaraa/Node-Shazam/blob/1dbfab50a60b61a8f018eada5449718b775bc09c/src/api.ts#L189-L190

Changing it to take from the middle of the signatures returned would return roughly to the original functionality.

You don't need to worry about this increasing calculation it wont resample and analyze the signature until you access the uri parameter

**Comment by duckyies** [comment]
Hey! I've changed it to loop over signatures starting from the middle until it gets a match

I noticed it only returns one signature if you call recognizeBytes() without passing 0, Number.MAX_SAFE_INTEGER so i used to just take the single one it returned

**Comment by Inrixia** [comment]
Ah yep! That's because it will exit on decoding the first 12 seconds to speed things up unless a offset and seconds is given. So you nailed it :)

**Comment by Inrixia** [comment]
Can I ask why you are using 
```ts
Math.floor(Math.random() * (signatures.length/2))
```
instead of 
```ts
Math.floor(signatures.length/2)
```
?

**Comment by duckyies** [comment]
oops thats my bad, i didnt mean to take a random index, i was testing the recognition with different parts of the song and completely forgot to remove that before commiting! thanks!
